### ISSUE TITLE
BUG: \ForumSystem\app01\views.py", line 38 return self._session[key]

### ISSUE THREAD

**Issue by KissMyLady** [likunhong01/ForumSystem#2]
**BUG 1:** 
Internal Server Error: /home/
Traceback (most recent call last):
  File "C:\Users\Administrator\Envs\forumsystem\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Administrator\Envs\forumsystem\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Administrator\Envs\forumsystem\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\A_Git_Code\ForumSystem\app01\views.py", line 38, in home
    response['uid'] = request.session['uid']
  File "C:\Users\Administrator\Envs\forumsystem\lib\site-packages\django\contrib\sessions\backends\base.py", line 54, in __getitem__
    return self._session[key]
KeyError: 'uid'
[27/Sep/2020 16:50:28] "GET /home/ HTTP/1.1" 500 86735
Not Found: /
[27/Sep/2020 16:50:36] "GET / HTTP/1.1" 404 3240

**Bug 2:** 
System check identified no issues (0 silenced).
September 27, 2020 - 16:51:58
Django version 2.2.1, using settings 'ForumSystem.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
Not Found: /
[27/Sep/2020 16:52:00] "GET / HTTP/1.1" 404 3240
Not Found: /
[27/Sep/2020 16:52:04] "GET / HTTP/1.1" 404 3240

**Comment by KissMyLady** [comment]
主页打开就有Bug, 请问还有更新这个项目吗 ?

**Comment by KissMyLady** [comment]
上传文章部分, 保存图片字段使用filter好像有bug的隐患
